language: node_js
node_js:
- 10.15.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: iyLeS023v7EXU5mSAXuHgD/U0dbbOFi9PJXAk/Cwtl2lpvxzHCyflmgsJM3A2N5+BvpmkdlXkKJAur1n5/aCRoEiA88wGHMF4pREXQU580TPPSdxytferLWdCBYvwd86v0Z5jUX1iNjTcRHLGnMJdoW1h8sHqy6M8bIb0mXFdmtHbVwYrzvxTqW4HNrVvhrSh53H3fin7Nu7cSN1wz5oSPZ9zlBxCVxxY9RGkucs4+ObDBNEzefUggWxouMQSFEdSoGzRqPhOCWsOcOLkn6EoXLt1XI8NL24RZatDj5p5jBJu4u3OjVAW5aiubYGdKUrJjAQwUgf7rFUAw6zY7FNekvC7CknYiueWvgALKCWE5nlr9fU8UM1V6jis61b8SqD6kt88nx5R0yyWLX1sMLRiYTWP2E/uAMHzvHtkNleH8sBGhCTuq4DrQ14cL5Alg939kmS0f3Z8v4m24a20gIvcdG2l1il6+GVb8A5Uz84SQqx+UHLSJdlfFAmHPt84xteXHa0UwshH8ZVipdN46YXlSBKOI75Bjx4jGgnuUuQiqq7NfZ2u2GruBZqqI3ep3gkpoeVAocECcJO3KWEirNDwywjkc9qAgI3m+iGw6z4DAQSdtY2Tn4QllLAS4pSCKVJ1jRXVghqwY/uwURlQeGC+SRJF/SFtfNFnRmU7HBD+CE=
  app:
    master: travis-example-production
    dev: travis-example-stage
