language: node_js
node_js:
  - 10.15.1
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: bHuTrBSTyLr+kx9y/ygXBo24INz5/90LpJL+cCUJPXMyCxZr6Uh/N+x39Q7YXhnPVFd7exmkM6NKg/fSSqHligOlY/QOusC1wh3Nb8YNG6rLTzd0TIrz86MsUrHJkqPo/OjxDDoE4OYGTsO2sWtLuluidgSKOLfJSFMxYPnz3/TC55PwpkXGAKAeU2W+rbvnm3JAFXyjE6U275M59vv1bcHC2yfWjWpVR9zgQfcEMFI3ig+Qd0wdZUWQMAXvkdvPCadu8LbldSuU6RZlocMxeed5cIId54d4GzFJJWShtYxbv0X01YyFYExzKD44ZqJ31xzq5lIQT2Tv70pNVG+fGsu0oGroqqzSe+g5kzDQaRbydGmJwYs2vYDwaUsZE31eFvpCTvu0CVcHrWUqNeKP5oV+hzp3/c/lYPLBTcRRzDWs81xEajtAwkSMm+XClBwRawVv0SE8V+QL+ZsVArQwWsvr5JGatrX1ya1nLUsqbzEkmINbgg8gCKfocrCMfR9/nl1M+MuqsG7yo/+gDG3vyD9eucY3J+HXY+Nqcb7whaHYRl2xVhT4TJ6L3LhCFYe0cYJ1n0bYN+bFL6RR1JNmAeMkG5SDPuZoC34fyctOKdRdYIx2l3HmJZrxFqnUIF0p9WtFt9WvJkPInhv0w9OViQXHbDI5rusJb97WcZgxCgM=

  app:
    master: travis-example-production
    dev: travis-example-stage
