language: node_js
node_js:
- 10.15.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: ByUYEi2EBPVMkbTVdpKx241wljuKgdATQySuDPiDZq5jr1n3vihqEYjE58pFMVnj26aETrMKi375VknyD197xoEfe17b8g+UHOA9HaJUufSP4BvKMbE1D5ptKwfzLksjlGkQ0+pacYTYgLZjIjecfXjtGpgpeKvUBjm0NaC/eubqwXe1w3dNEgnw380myiEqdgnniWe0wbJctZO1KGH42nyOBDpU8jGZG6jQiurkIeOB5U03K3mAgqTbOZd4TMm1HFZuBrtlsK9F2KMuVNWA/xzj0+kxZv/zlS4vaeowVF3VH/Zk8wLD7QKmecPFTBaf+eCySiJLTujBcZL3svQhjwxtQgOHMQUkM6asbMk1mED8a1fDBB7pfeMyY0BVfCSPHFyc9bVedwXW0HCbK4Z0Hj63J+AOZJaWpEcQYkkxTl8cPGHn75hX/RIAAzxU/eTpHPbesCOzvtdju8D+90jSvK3oO1gMBnsXszOSE26uupPB4QcBFYfoh8YgqwPOarb5g/4J8ct06dXT4TBC7wSZJYZQnlwl2u4TMqEmagXAIoUXFFJkNvexVbYpmcp8klLt55Sn/cCRgLg6qgx2QXwVeZ+oj86k+HlGyDDZGsPQeBwwvL3KfrE5+9BF12JFRge0/Ck+2Sj6xxccRYK8c3F8h5JlJWDAVHx5uYvT744C7fc=
  app:
    master: travis-example-production
    dev: travis-example-stage
