language: node_js
node_js:
- 10.15.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: JPyv7uLSJl27Mf5FatmC0DVJ+m52J7GBuFIaszPJtYqn6sz6+7+ICIahFhWLtnYqtmVGUQylqsNbuSIEhVVuO4XZduhh9jmAQ/6PQoryghIulmEhw/Nqyt6w35wZ3+JgUssUNnzphxTCNh/qWplxSJc3pxj2CAGv+g4ZPycTrnLXC8tU7NTeKYtn88Bb/RTAI54bt1547XG+WdSVp/5B62UsuJQlVHRLgeGoqA4740vh/s+pq8Bty3dpgACvj/plS5C8BKPJRnJc1T4WFhums0LKWKZkpforcbA++nime3IvoP5G8BGH2F+sovtLsczLlKfqnvjx/Hetu7wAY1a28KaAAiH6fq/sc0XCCqcqHLQ0x7jd/lRF+GzC3k/fkfGaRv8JWOfc7B+/rDnCEMbMBUFN5l59QdVNDw1jOpiw63QwcTvki/Fy25xspuUE9cQ+a0m+RKD9igMH/+ILSkFhsMRoEfFyWbLuk0OjDkOfBxW+3NeoZfDgjcysNdZ/69dHWtYeSf8MtYfCEcwMMPfQLyXJq6kZuCNlznQs5RrEHQ6fWw6DUSiByKSufaeKnA2gDLijgv/g+zpRnrP8dft2mveY8JlJk9g2VZP6hNyoUiuD46rFAYRRAgsqgCGJnRQtuDBVDwLEQfH0WdUnV9ACcmYS3nAcjpiTvPslwSs7Xx8=
  app:
    master: travis-example-production
    dev: travis-example-stage
