language: node_js
node_js:
- 10.15.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: Ro7B8eL+a8s9ZvYBDJmV2GfMFo8g9aQt90gaGJJktqbKCqbzC9STgrtWXVOFIYp5fCqG5ee93rOsKZ2z7wXw/U0rTpTHRm4y3/z0bcSjmHzYrYYqvBNpqtf6v06l+EoTE0CfwstJNzB51gQi2B7zBYZSwxUzXf4ZRATXJb9tv5SJME7LfkJpWIkrs54RLRn86hm3iZIGpog0cndP80dLqLdxBqQ8g5iOod0Xym6k06Ha4dUezX6tLrw0OiFzHEr/ksoY8yyYjrzwCeXhG8X3ZBljlAXdl2ssvIRomzGdZA9EJt8yDMDtWmo21bWPjjyMtXergVYshS+P0xSJtvMZ2kS5NDJSG4reLsDdO4zfra5KSjR/T/yb5SfrPPGUCND2xPUjnL3iQMAJ5/G2Eeaj5kTV44zC8878QICZ+yPfQLmwkDSSfpkKN9vXae0cyl4Hn+bB711KcnlTmYBeL5P75mP4RlLHj8/kjHetkrwmNoEsn1FI7Zi6gq55Si+XhozSMfr5h6LjoLuVaU2mdBkQNLixKPzBxYsMfswLLOYZiflTM2kbbKMsgx04VCVAwJv6uSJmaW7fUOyQ4D3wcKCZf16qgroyPCq7057mKrHlYjh628SHlk4nGlDv8+U5BFw/cNmzL4/5JZyGHg50YdI8qoMqT6llD43QX2wg02bGrUQ=
  app:
    master: travis-example-production
    dev: travis-example-stage
