language: node_js
node_js:
- 10.15.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: lCKlWvW1A5uzJXHd8J0bUsGvqgsQjzHN3lD1JsCo9+T8fS3qduZnzrfR6V91c/VkMVqNaN7YLrlzt41gu+1EB901w86CVpxUrRXUZgYxvnGBBjognpFeXQKPQu8jtWqPHWwq8TRDxF6ZcQGHJ2h4hEUP/h3T7ipAuRucXaOvl7ff6FUCNiB0Vtrcnu4Frn/XgLnMsMC/0EIFOQKbNll4QVCgzVCTfwVAaPSiTfmrWxESrLKMzF9kiEUqpUcq6N69T9nfvsC8HfHYyTFoCxlQ1wqJmZygn6oql8HI1entmkqn1Yog+bB63ee03CgLXvoRLQmP35PVsCF+spIewTHvzd8rxzDmhfDKsv7zP4S7VuOdhTTIsmPdKtpxQNXUjetjaMkNQr0wFYbTtPbrBcQmxzNebjm64fNJIRbyI5JLSYHz9gJy6N6iBJkpFVKJM5Fh0UL9kR3vN9jDyBkAHXsAUjBj2vzWrTaX0D8BYINai5rkHYi1vzteOmnz2B3EZol9VIQ6cRQp8a9QqMEHkGeg0g/dFgrJLIaoZkz0uFDAntIq8Ix03p57OIinyiB3dLUto8LEq++7F8gtu7IfSdM8yqdDlJV21ZiNcdrM3DiVLXxaL+17/NE1K7q4nfZ9e2ZtPVp7lW6Dav2JcCGJVHzg0VO7/O81N08zYuUC2C179dA=
  app:
    master: travis-example-production
    dev: travis-example-stage
