language: node_js
node_js:
  - 10.15.1
install:
  - npm install
script:
  - npm run test
before_script: chmod 0777 ./node_modules/.bin/mocha
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: SJHtyfoNy8C792T9iKgg14JaKm7/+wqDC61p8/dgMVyL9wMyn0UkRfoyMon0oK8zsy1xyuGos697S8qXeq8dHDxBfksmnnzTkFLJxukgSNlTpP1M0suzXJ07uhpxidJR3I10N9flOSHD0OagS6IGuOH0gqtFmlcdHwGG+qo9+i3VwO/jvhrDDcj2TULVtakqzT27tB+et8pk+yTGhy7sIgTgjqOvPdk/sFTfek9v82Mbf47/XT/nOexysRTT5MtC3ArvC0mLexIo8eZX18t8ZAmAaxz3SQMjX8WKI556c2qvLbENzEv3YoNY5BM1MG+w6rwg6tRu+E1IeR1ZxHwC1SzquzCkQwEdNTIXhNjv9EW2RR29IhaEzHAIZqLYGJZ9wWYbzkmXxd91aMY1AsxDQIJKlFzxNZvBbpStJGF6ciC235bhkzr8+B+PH/8Rat5KReqjSu/W4ECdSQE8emdd6UGn4Q6QP158JCxq8m3HbsikTpu2fIMqg+X9hqbt3mBYHCf+iWJgAgBVb6qqZrI6ekMwy06YZ39Hc8bzL7x0OWVXMrYZS2SD5uLK8JrtLo1nchdO1epAKsHkZPV/gz+CdHNnpag0L9ILNVMmVJVt0BX+09yL5lzv5u1aIUS7nG5bm/zRnCW5d4O4ilCbNNoV8o6flF75WuL7lB37YvwZOno=

  app:
    master: travis-example-production
    dev: travis-example-stage
