language: node_js
node_js:
  - 10.15.1
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: Gg0D4d1QsExClFW8Oj64wpE8XOeMWtPXHEUjkn7dskyhZuUva3CP3a8Gfsl1r23dODrj/kgMOtIyD4888ywdXcHC72qFnGSvQqIDXSN50WtFkzyBTDfbnjVlWJzn75Ao60wIpHYcUU7zmXTts25MNxpBo9OMhjZAtLXrY+24R85qRzTkWjBxI0F0M3V/f38qt2pKzdicM2M5gkRrY5JB2wul6HfFoAU2k7umQd/GLpuqaRQis4L56EbiAQZxwVLdHdpReaqVTWJh+OuZpKgJ0GC0RulbpiKCwP2I1HCH6Lb3Jo5L6AtDUAijkYnfxPJn279OWlkFwKNrKW1U5BlnD9gOImDMGNgKqawA32UFUtmnkT2T9OyEXqWs9s5RLUsFn7ZCjU+E5vvE3/vokWG04u1f+fi/jhHAyocGxMDeIj44WR36aRMhvUNzii1qlLPs2Grt/4mcni1CIqzWL2iyoP3VJFFHIs7GvQRWaOWibcpalQBP6CBjAZV5WPXD/L1Gs1V4htJUEYt45DqmM0P8yIMEa4Fjc2qLAFF0b97VL9qA4ys7trqc7nZLBHFqmwEmFlhMhp75pNobvGikSlifHxQ1tWn/3qIDPGo4zpH+mEm053aEsBj8z0kUmCNpNaLp7DNaemrQshwx57xZ1sNB2lCUE2z8E0PeSNNHk++fZ8w=

  app:
    master: travis-example-production
    dev: travis-example-stage
