language: node_js
node_js:
- 10.15.1
install:
- npm install
script:
- npm run test
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  api_key:
    secure: dJrQWXCJ1DWOD/Rt4GC0iuVgtKDCQrQkvhzGL60Lb6Owy2BsTm6RytesnyVsZQ/uqLQanVfzTntkTXO/LRpaMlSYJtmC8IvzCRxgk330NrQTB4UNm1G7JeYmN0xIZAgDtdSPjdfllWhi4mpgdy9rCu6cqb+aSxDzZkgGa55JewT9nTi/AjGlk8w0AnMjwA9cX9hGRUB16Zaf5FFNftneA/Q5oVWk6T2ZHwuoBrRjtdX/eNg0e/w6d5D81uMfOfe9rcO2Yy4jM6OqH3a1TU8nRZsJaKuj4apWSi/Zk8m+fatElHgj/hxk3o0rH7pxvnM1Faxv8jtOVgC9AHbScBw+1Z9Hzxx3ZyfPmMSgNTcwzQOTS1WceqNUEPgMp9fu2Wp14iuOV/6DTb2hieoexXBqA2FRwPAN22nhrjhuAWtADT2WIM7pVeJ8q/cKjfS+Vt5B03hsBwTcZZ2FwKB1kQfJIQkl1wr7AKVfh7FaTfxTqb3Ja26tb6jrZq8D/vyzLFrmwhDNkXDlMaP4iGqpC3lNe8EzCPZXw3Qgx7XSYjtAExMdVJMaHDabAVa6mK4oXDT2R3cnFAr32PLyqD45ktYYtokqEYPccPbbdSk1Te0FfcST2Coklnhwf2YT8r2TSW5S9x8r5ANkcJ9q2eI2tRRcMpyrv7lfSUSZ0wa15bJ+DQ8=
  app:
    master: travis-example-production
    dev: travis-example-stage
