language: node_js
node_js:
  - 10.15.1
install:
  - npm install
services:
  - postgresql
env:
  global:
    - NODE_ENV=test
script:
  - npm run lint
  - npm run test
before_script:
  - chmod 0777 ./node_modules/.bin/mocha
  - chmod 0777 ./node_modules/.bin/eslint
  - psql -c 'create database book_test;' -U postgres
  - psql -c "CREATE USER  WITH PASSWORD '1994yigit44';" -U postgres
  - npm run build
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: edoXDu4oesPtYQmzZZqEu+KoksHfBMX7SbtzCPKo8DaYlo1OzN2/5Hmtwab2H2fbjyHkHkUrdBbOVn2kRyq8tgRMG9Jx+LPbHv4Xy80N2HO5EJSHWHBz/BreRFWFP+VBXi1QEvafAsGJnFQ5rtMSeCAFTtIS50exTG+r8SNBBYt+QL8UU9nqvhpKAtNXLtT6FsBd8mZ2jzUDm0I1glk+OPdvoM+122VfKpYTGb9bjOBNhAXoTzXvbZsEQBzRVuHwLbokDrkMV4wqB/iwVLqxeHoJLF0160C3XsNjQoYH0pVoI+wiTFpeO9Sw2/qYdbymQsJalOXaTRJECo3620EI3wTe6R181EzTdZPafIGaxUbSHPGUVDEJbvRVccvE0UiEKYeUyUT8TKo7YGThKQLEpq3CKSLfIJ2KCey93V47p0kNmRMmUOAkJdWqEBca/lY/1HVwerG+qUFlzER9VhGZUxQPDdJWsPLilpUj1Bz5K4wXY1ojY3iuj43k1rx8mdDxzBSSF+vp3w7vob3jplFDmA9mquF+vy7Tqqd6zLq0J7GvJ07OvJ1wrGi0bY9QpNIu4FR3k+58nXcNkc70MZBXvhYKdbhCJsqr+2foOTWrt6ORkeDu/ZWik9d3OCOpj13b0KtPnsk5/4bQTxfJTDYqdJ+rjLqLA2nWogJIhLZpYCg=

  app:
    master: travis-example-production
    dev: travis-example-stage
