language: node_js
node_js:
  - 10.15.1
install:
  - npm install
script:
  - npm run test
before_script: chmod 0777 ./node_modules/.bin/mocha
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: bt+sdotSg9kz/6r1iY7bc4y6pDFTjp03PvnOj+sMbynXyYRapYw7U289G7EVPtXu/l/rsjuErDvzn+Pm2jdSLBSi2rk33U0U2TFXDMwJKrk5ZN5TrCwIGYSSPguaU8GLWVh5XIcylpv6EhR7ZZjL4yJCU5br+jeUCVQ59Vmw6iAyBsfRPwzC+Cs2Bfyc6eeDvA15jpIxamryrbmG1/7ROQRfJzISJfVdwiCCvizrHRzrOdW97vyaGFuVfDBkazrLNmgyXbHXIrPzBZikuU6pV2Eou5D8IMoLq3saoY71QJuMP5tQTi0XLJrERUk05TrBibCyzNh5lfHuFbvnkQHJK80F9pkCBqLrp+W7mnQlujGqdfapLCVeWwO7+qsEkIypTokQLbkBjroVp/CRFpYic3SOLdlT7TwDCVW/Y7vBBjGwTNDTbidfyPNO8II/GV5cQfQbO4Ww5hOtt/5PY/k3J+FmeEPTy6u4o2qVhS0rtdcXb/AK2vUHQ5Kjk8gKosPDiQzvTEkJYfeMVxh/y8k25BB6JrOubE+eP8G/xJGqHDJmXmQe3Kwa2U2UVSN6kv9B/21fS1fcQitD4ejWmjDkC2JMck+8L0OYxebjd7ak97/oiEHt6I7bjy1M7pAgvuhUB7i3LyvPeaADh6b/OjEjduC0x6HHILqQllaLYzOcXrU=
  app:
    master: travis-example-production
    dev: travis-example-stage
dd:
  secure: CFOo5EqLCu9vRRz4nsEBZ18g7iiFTWbcJRtGt0cdv93Z+9/6RSmRECwvdWaWVJDPz1n2yRy26AnNC+oDLqAXyxcmiSk/l3eSczvqhQsj90u+IGgohqX00B7jLxLxXKaNnX2qoqQlsEvAZan85MsMouMDQpWvoSjwfiYtOr2fX3uUUGosDlsamq8fxX6YJcHmZlh4zTtoEWivS9vxWQnHdRe2Opnixf442o/fWP5BpPyB9bCaB0TZGS9o+1ZpTX0GydKW88nHeuR/VTNiwql5mFrsXpqqYtgxr3IB3itEgBLEJwzh/DoNirrPZoD60RJ3v3PKQKKInyvK+W0VYwNDdOGPDKdQBvaqYc/wm84sd8xqPa+T/03NEKtsJBPCgxkG1uyL3SOLurUv+rXri06UuGdfPVqPF78a3vJcIZt189Fb6C+9kgG09ZS4dHrVzrQsxq+YbXYslr8vc5klpONXQs9avIRQa0CD2O099ycLpY6vTDBkVFSJfxXQ+RFq59q+nkx70TAg/wvVvDa490s/laZy1fxtiBS7I6C+iQNwSMzSmqHh2TI5VSSRSd27daugWpiBub4XiLsXsoTjYr4zn7ailno0zd5V4RcgW9/H5ayvcGCcdVnb53slbqwWI5w8GsomlHLehTWm+XjH7KiUKnCgTvVEapBGZ1IJaLkuCLs=
